import type {RequestInstance} from '../common/request';
import type {paths} from '../types/v2'; // generated by openapi-typescript

/**
 * 인증 관련 API
 *
 * @description 인증과 관련된 API 기능을 제공합니다.
 */
export const auth = (_request: RequestInstance) => {
  return {
    /**
     * API secret 를 사용한 토큰 발급
     *
     * @description API secret 를 사용한 토큰 발급
     * API secret 를 통해 API 인증에 사용할 토큰을 가져옵니다.
     */
    token: (
      body: paths['/login/api-secret']['post']['requestBody']['content']['application/json']
    ) => {
      return _request.POST('/login/api-secret', {body});
    },
    /**
     * 토큰 갱신
     *
     * @description 토큰 갱신
     * 리프레시 토큰을 사용해 유효기간이 연장된 새로운 토큰을 재발급합니다.
     */
    tokenRefresh: (
      body: paths['/token/refresh']['post']['requestBody']['content']['application/json']
    ) => {
      return _request.POST('/token/refresh', {body});
    },
  };
};
