import type {RequestInstance} from '../common/request';
import type {paths} from '../types/v2'; // generated by openapi-typescript

/**
 * 빌링키 관련 API
 *
 * @description 빌링키와 관련된 API 기능을 제공합니다.
 */
export const billingKeys = (
  _request: RequestInstance,
  options?: {storeId?: string}
) => {
  return {
    /**
     * 빌링키 단건 조회
     *
     * @description 빌링키 단건 조회
     * 주어진 빌링키에 대응되는 빌링키 정보를 조회합니다.
     */
    getBillingKey: (
      params: paths['/billing-keys/{billingKey}']['get']['parameters']['path']
    ) => {
      return _request.GET('/billing-keys/{billingKey}', {
        params: {
          path: {billingKey: params.billingKey},
          query: {storeId: options?.storeId},
        },
      });
    },
    /**
     * 빌링키 삭제
     *
     * @description 빌링키 삭제
     * 빌링키를 삭제합니다.
     */
    deleteBillingKey: (
      params: paths['/billing-keys/{billingKey}']['delete']['parameters']['path']
    ) => {
      return _request.DELETE('/billing-keys/{billingKey}', {
        params: {
          path: {billingKey: params.billingKey},
          query: {storeId: options?.storeId},
        },
      });
    },
    /**
     * 빌링키 발급
     *
     * @description 빌링키 발급
     * 빌링키 발급을 요청합니다.
     */
    issueBillingKey: (
      body: paths['/billing-keys']['post']['requestBody']['content']['application/json']
    ) => {
      return _request.POST('/billing-keys', {
        body: {
          ...body,
          storeId: body.storeId || options?.storeId || undefined,
        },
      });
    },
  };
};
