import type {RequestInstance} from '../common/request';
import type {paths} from '../types/v2'; // generated by openapi-typescript

/**
 * 현금 영수증 관련 API
 *
 * @description 현금 영수증과 관련된 API 기능을 제공합니다.
 */
export const cashReceipts = (
  _request: RequestInstance,
  options?: {storeId?: string}
) => {
  return {
    /**
     * 현금 영수증 단건 조회
     *
     * @description 현금 영수증 단건 조회
     * 주어진 결제 아이디에 대응되는 현금 영수증 내역을 조회합니다.
     */
    getCashReceipt: (
      params: paths['/payments/{paymentId}/cash-receipt']['get']['parameters']['path']
    ) => {
      return _request.GET('/payments/{paymentId}/cash-receipt', {
        params: {
          path: {paymentId: params.paymentId},
          query: {storeId: options?.storeId},
        },
      });
    },
    /**
     * 현금 영수증 수동 발급
     *
     * @description 현금 영수증 수동 발급
     * 현금 영수증 발급을 요청합니다.
     */
    issueCashReceipt: (
      body: paths['/cash-receipts']['post']['requestBody']['content']['application/json']
    ) => {
      return _request.POST('/cash-receipts', {
        body: {
          ...body,
          storeId: body.storeId || options?.storeId || undefined,
        },
      });
    },
    /**
     * 현금 영수증 취소
     *
     * @description 현금 영수증 취소
     * 현금 영수증 취소를 요청합니다.
     */
    cancelCashReceipt: (
      params: paths['/payments/{paymentId}/cash-receipt/cancel']['post']['parameters']['path']
    ) => {
      return _request.POST('/payments/{paymentId}/cash-receipt/cancel', {
        params: {
          path: {paymentId: params.paymentId},
          query: {storeId: options?.storeId},
        },
      });
    },
  };
};
