import type {RequestInstance} from '../common/request';
import type {paths} from '../types/v2'; // generated by openapi-typescript

/**
 * 에스크로 관련 API
 *
 * @description 에스크로와 관련된 API 기능을 제공합니다.
 */
export const escrow = (
  _request: RequestInstance,
  options?: {storeId?: string}
) => {
  return {
    /**
     * 에스크로 배송 정보 등록
     *
     * @description 에스크로 배송 정보 등록
     * 에스크로 배송 정보를 등록합니다.
     */
    registerEscrowLogistics: (
      body: paths['/payments/{paymentId}/escrow/logistics']['post']['parameters']['path'] &
        paths['/payments/{paymentId}/escrow/logistics']['post']['requestBody']['content']['application/json']
    ) => {
      const {paymentId, ...processedBody} = body;

      return _request.POST('/payments/{paymentId}/escrow/logistics', {
        params: {
          path: {paymentId},
        },
        body: {
          ...processedBody,
          storeId: processedBody.storeId || options?.storeId || undefined,
        },
      });
    },
    /**
     * 에스크로 배송 정보 수정
     *
     * @description 에스크로 배송 정보 수정
     * 에스크로 배송 정보를 수정합니다.
     */
    updateEscrowLogistics: (
      body: paths['/payments/{paymentId}/escrow/logistics']['patch']['parameters']['path'] &
        paths['/payments/{paymentId}/escrow/logistics']['patch']['requestBody']['content']['application/json']
    ) => {
      const {paymentId, ...processedBody} = body;

      return _request.PATCH('/payments/{paymentId}/escrow/logistics', {
        params: {
          path: {paymentId},
        },
        body: {
          ...processedBody,
          storeId: processedBody.storeId || options?.storeId || undefined,
        },
      });
    },
    /**
     * 에스크로 구매 확정
     *
     * @description 에스크로 구매 확정
     * 에스크로 결제를 구매 확정 처리합니다
     */
    confirmEscrow: (
      body: paths['/payments/{paymentId}/escrow/complete']['post']['parameters']['path'] &
        paths['/payments/{paymentId}/escrow/complete']['post']['requestBody']['content']['application/json']
    ) => {
      const {paymentId, ...processedBody} = body;

      return _request.POST('/payments/{paymentId}/escrow/complete', {
        params: {
          path: {paymentId},
        },
        body: {
          ...processedBody,
          storeId: processedBody.storeId || options?.storeId || undefined,
        },
      });
    },
  };
};
