import type {RequestInstance} from '../common/request';
import type {paths} from '../types/v2'; // generated by openapi-typescript

/**
 * 본인인증 관련 API
 *
 * @description 본인인증과 관련된 API 기능을 제공합니다.
 */
export const identifyVerifications = (
  _request: RequestInstance,
  options?: {storeId?: string}
) => {
  return {
    /**
     * 본인인증 단건 조회
     *
     * @description 본인인증 단건 조회
     * 주어진 아이디에 대응되는 본인인증 내역을 조회합니다.
     */
    getIdentityVerification: (
      params: paths['/identity-verifications/{identityVerificationId}']['get']['parameters']['path']
    ) => {
      return _request.GET('/identity-verifications/{identityVerificationId}', {
        params: {
          path: {identityVerificationId: params.identityVerificationId},
          query: {storeId: options?.storeId},
        },
      });
    },
    /**
     * 본인인증 요청 전송
     *
     * @description 본인인증 요청 전송
     * SMS 또는 APP 방식을 이용하여 본인인증 요청을 전송합니다.
     */
    sendIdentityVerification: (
      body: paths['/identity-verifications/{identityVerificationId}/send']['post']['parameters']['path'] &
        paths['/identity-verifications/{identityVerificationId}/send']['post']['requestBody']['content']['application/json']
    ) => {
      const {identityVerificationId, ...processedBody} = body;

      return _request.POST(
        '/identity-verifications/{identityVerificationId}/send',
        {
          params: {
            path: {identityVerificationId},
          },
          body: {
            ...processedBody,
            storeId: processedBody.storeId || options?.storeId || undefined,
          },
        }
      );
    },
    /**
     * 본인인증 확인
     *
     * @description 본인인증 확인
     * 요청된 본인인증에 대한 확인을 진행합니다.
     */
    confirmIdentityVerification: (
      body: paths['/identity-verifications/{identityVerificationId}/confirm']['post']['parameters']['path'] &
        paths['/identity-verifications/{identityVerificationId}/confirm']['post']['requestBody']['content']['application/json']
    ) => {
      const {identityVerificationId, ...processedBody} = body;

      return _request.POST(
        '/identity-verifications/{identityVerificationId}/confirm',
        {
          params: {
            path: {identityVerificationId},
          },
          body: {
            ...processedBody,
            storeId: processedBody.storeId || options?.storeId || undefined,
          },
        }
      );
    },
    /**
     * SMS 본인인증 요청 재전송
     *
     * @description SMS 본인인증 요청 재전송
     * SMS 본인인증 요청을 재전송합니다.
     */
    resendIdentityVerification: (
      params: paths['/identity-verifications/{identityVerificationId}/resend']['post']['parameters']['path']
    ) => {
      return _request.POST(
        '/identity-verifications/{identityVerificationId}/resend',
        {
          params: {
            path: {identityVerificationId: params.identityVerificationId},
            query: {storeId: options?.storeId},
          },
        }
      );
    },
  };
};
