import type {RequestInstance} from '../common/request';
import type {paths} from '../types/v2'; // generated by openapi-typescript

/**
 * 특정 PG사 관련 API
 *
 * @description 특정 PG사에 국한된 API 기능을 제공합니다.
 */
export const forSpecificPg = (_request: RequestInstance) => {
  return {
    /**
     * 카카오페이 주문 조회 API
     *
     * @description 카카오페이 주문 조회 API
     * 주어진 아이디에 대응되는 카카오페이 주문 건을 조회합니다.
     * 해당 API 사용이 필요한 경우 포트원 기술지원팀으로 문의 주시길 바랍니다.
     */
    getKakaopayPaymentOrder: (
      query: paths['/kakaopay/payment/order']['get']['parameters']['query']
    ) => {
      return _request.GET('/kakaopay/payment/order', {
        params: {query},
      });
    },
  };
};
