import type {RequestInstance} from '../common/request';
import type {paths} from '../types/v2'; // generated by openapi-typescript

/**
 * 프로모션 관련 API
 *
 * @description 프로모션과 관련된 API 기능을 제공합니다.
 */
export const promotions = (
  _request: RequestInstance
): {
  getPromotion: (
    params: paths['/promotions/{promotionId}']['get']['parameters']['path']
  ) => ReturnType<RequestInstance['GET']>;
} => {
  return {
    /**
     * 프로모션 단건 조회
     *
     * @description 프로모션 단건 조회
     * 주어진 아이디에 대응되는 프로모션을 조회합니다.
     */
    getPromotion: (
      params: paths['/promotions/{promotionId}']['get']['parameters']['path']
    ) => {
      return _request.GET('/promotions/{promotionId}', {
        params: {
          path: params,
        },
      });
    },
  };
};
