import createClient from 'openapi-fetch';
import type {paths} from '../types/v2'; // generated by openapi-typescript

export function createRequestInstance(baseURL: string, Authorization?: string) {
  return createClient<paths>({baseUrl: baseURL, headers: {Authorization}});
}

export type RequestInstance = ReturnType<typeof createRequestInstance>;

export default createRequestInstance;
